version: "3.9"

services:

  questionnaire-backend:
    container_name: questionnaire-backend
    build: ./
    ports:
      - "8000:8000"
    restart: always
    entrypoint: /entrypoint.sh
    volumes:
      - ./:/questionnaire-backend
    depends_on:
      - questionnaire-db
    command: ["healthy-check.sh", "questionnaire-db:5432"]


  questionnaire-db:
    container_name: questionnaire-db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: .env

  redis:
    image: "redis:alpine"

volumes:
  static_volume:
  pgdata:
